[package]
name = "cli"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
provisioning = { path = "../provisioning" }
identity = { path = "../identity" }
settings = { path = "../settings" }
anyhow = { workspace = true }
tokio = { workspace = true }
